# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 557ca7ddc9f47ed0c8eb39b7c5577247589834e538e54dc2459366073593e723ef49e2bc28d594b6827c41719ca08f001a79f1e6fb537822a6a9e9f9bb82ccb0

test:
  secret_key_base: 882a116db857e4b444b4b81da0523076836ff1419678344f00d5d32cef337eff6f00d9a044217f50e8013e1f5f67158230b7e153260d50fefd3c123ed561564b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
